=== delias96/W8YSQV_XMLGYAK/W8YSQV_09.28/ED_konyv.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT konyvek (konyv)*>

<!ELEMENT konyv (cim,kiadaseve,kiado,szerzok+,absztrakt?)>
<!ATTLIST konyv
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT cim (#PCDATA)>
<!ATTLIST cim
  xmlns CDATA #FIXED ''>

<!ELEMENT kiadaseve (#PCDATA)>
<!ATTLIST kiadaseve
  xmlns CDATA #FIXED ''>

<!ELEMENT kiado (#PCDATA)>
<!ATTLIST kiado
  xmlns CDATA #FIXED ''>

<!ELEMENT szerzok (szerzo)+>
<!ATTLIST szerzok
  xmlns CDATA #FIXED ''>

<!ELEMENT absztrakt (#PCDATA)>
<!ATTLIST absztrakt
  xmlns CDATA #FIXED ''>

<!ELEMENT szerzo (#PCDATA)>
<!ATTLIST szerzo
  xmlns CDATA #FIXED ''>

=== delias96/W8YSQV_XMLGYAK/W8YSQV_09.28/ED_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyvek SYSTEM "ED_konyv.dtd">
<konyvek>
<konyv id = "1">
<cim>Az xml</cim>
<kiadaseve>2000</kiadaseve>
<kiado>Libri könyv kiadó</kiado>
    <szerzok>
        <szerzo>Horváth Béla</szerzo>
        <szerzo>Kelemen Árpád</szerzo>
    </szerzok>
    <absztrakt> XML detail </absztrakt>
</konyv>
<konyv id = "2">
<cim>Tiszta kód</cim>
<kiadaseve>1991</kiadaseve>
<kiado>Alexandra könyv kiadó</kiado>
    <szerzok>
        <szerzo>Kiss Jenő</szerzo>
    </szerzok>
    <absztrakt> XML detail2 </absztrakt>
</konyv>
<konyv id = "3">
<cim>A React csodálatos világa</cim>
<kiadaseve>2010</kiadaseve>
<kiado>Libri könyv kiadó</kiado>
    <szerzok>
        <szerzo>Kiss Imre</szerzo>
    </szerzok>
    <absztrakt> XML detail3 </absztrakt>
</konyv>
</konyvek>
